name: Workflow C

on:
  push:
    branches:
      - main

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16, 18, 20]

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
