name: Workflow C (Matrix)

on:
  push:
    branches:
      - main

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16, 18, 20]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      
      - name: Print Node.js version
        run: node --version
      
      - name: Print NPM version
        run: npm --version
